[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_nft_anchor = "9iTai8UpbNfEweBNyvFVRRpPm4jKPfbnmPn8NGwdYJpp"

[registry]
url = "https://api.apr.dev"

# Done
[provider]
cluster = "devnet"
wallet = "/Users/giftea/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
